---
title: "Priors"
author: "Nicolas Banholzer"
date: "2023-07-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries

```{r}
library(tidyverse)
library(LaplacesDemon)
source("../utils/trans_risk.r")
source("../utils/plotting.r")
```


## Quanta

```{r}
q_dat <- data.frame(x = seq(0, 200, 0.1)) %>%
  mutate(y = pq(x))

prev_est <- data.frame(
  study = c("Andrews (2014)", "Escombe (2008)", "Nardell (1991)", "Riley (1962)"),
  x = c(0.89, 8.2, 12.5, 1.25)
) %>%
  mutate(y = pq(x))

q_pl <- ggplot(mapping = aes(x = x, y = y)) +
  geom_line(data = q_dat, direction = "vh") +
  geom_segment(data = prev_est, mapping = aes(xend = x, yend = 0, color = study), linetype = "dotted") +
  geom_segment(data = prev_est, mapping = aes(yend = y, xend = 0, color = study), linetype = "dotted") +
  geom_point(data = prev_est, mapping = aes(color = study), shape = 17, size = 2) +
  geom_text(data = prev_est, mapping = aes(label = study, color = study), size = 8 / cm(1), nudge_x = log(1.35)) +
  scale_x_continuous(expand = expansion(mult = c(0,.025)), breaks = c(0, 1, 10, 100, 200), trans = scales::pseudo_log_trans(base = 10)) +
  scale_y_continuous(expand = c(0,0), labels = scales::percent_format(suffix = "")) +
  scale_color_manual(values = wes_palette("Cavalcanti1")) +
  labs(x = "Quanta generation rate (quanta/h)", y = "Cumulative probability (%)") +
  theme_custom() +
  theme(legend.position = "none")

q_pl
save_plot(q_pl, pdf_file = "../illustrations/prior-q.pdf", w = 12, h = 8)
```


## Viral inactivation rate

```{r}
plambda <- function(x, disease = "TB") {
  plnorm(x, meanlog = log(1), sdlog = 1)
}

lambda_dat <- data.frame(x = seq(0, 10, .01)) %>%
  mutate(y = plambda(x))

prev_est_vir <- data.frame(
  study = c("Loudon (1969)", "Lever (2000)", "Gannon (2007)", "Klein (2014)"),
  x = c(log(2)/6, log(2)/(5/60), log(2) / 1.5, log(2) / (0.5/(log(20/100, 0.5))) )
) %>%
  mutate(y = plambda(x))

lambda_pl <- ggplot(mapping = aes(x = x, y = y)) +
  geom_line(data = lambda_dat, direction = "vh") +
  geom_segment(data = prev_est_vir, mapping = aes(xend = x, yend = 0, color = study), linetype = "dotted") +
  geom_segment(data = prev_est_vir, mapping = aes(yend = y, xend = 0, color = study), linetype = "dotted") +
  geom_point(data = prev_est_vir, mapping = aes(color = study), shape = 17, size = 2) +
  geom_text(data = dplyr::filter(prev_est_vir, study == "Lever (2000)"), 
            mapping = aes(label = study, color = study), size = 8 / cm(1), nudge_y = 0.05) +
  geom_text(data = dplyr::filter(prev_est_vir, study == "Klein (2014)"), 
            mapping = aes(label = study, color = study), size = 8 / cm(1), nudge_y = -0.05, nudge_x = 0.1) +
  geom_text(data = dplyr::filter(prev_est_vir, study == "Gannon (2007)"), 
                                 mapping = aes(label = study, color = study), size = 8 / cm(1), nudge_x = 0.125) +
  geom_text(data = dplyr::filter(prev_est_vir, study == "Loudon (1969)"), 
                                 mapping = aes(label = study, color = study), size = 8 / cm(1), nudge_x = 0.125, nudge_y = 0.025) +
  scale_x_continuous(expand = expansion(mult = c(0,.025)), breaks = c(0, 0.5, 1, 2, 5, 10), trans = scales::pseudo_log_trans(base = 10)) +
  scale_y_continuous(expand = expansion(mult = c(0,.025)), labels = scales::percent_format(suffix = "")) +
  scale_color_manual(values = wes_palette("Cavalcanti1")) +
  labs(x = "Viral inactivation rate", y = "Cumulative probability (%)") +
  theme_custom() +
  theme(legend.position = "none")

lambda_pl
save_plot(lambda_pl, pdf_file = "../illustrations/prior-lambda.pdf", w = 12, h = 8)
```