---
title: "Clinical Data"
author: "Nicolas Banholzer"
date: "2023-11-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries

```{r}
library(tidyverse)

source("utils/plotting.r")
```


## Data

```{r}
df <- readRDS("data-clean/clinical/clinical-data.rds") %>%
  filter(between(month(date), 10, 11))

modeled_days <- list.files("data-clean/patient-tracking/linked-and-imputed")
modeled_days <- gsub("[[:punct:]]rds", "", modeled_days)
modeled_days <- as.Date(modeled_days)
modeled_days_abbrv <- format(modeled_days, format = "%b %d")
```


## Descriptives

### Diagnosed/Suspected TB over time

```{r}
diag_tb <- df %>%
  mutate(
    date_in_model = format(as.Date(date), format = "%b %d"),
    date_in_model = ifelse(
      date_in_model %in% modeled_days_abbrv, date_in_model,
      "Not modeled"
    ),
    date_in_model = factor(
      date_in_model,
      levels = c(modeled_days_abbrv, "Not modeled")
    )
  ) %>%
  group_by(patient_id, date) %>%
  slice(1) %>%
  ungroup() %>%
  group_by(date, date_in_model) %>%
  summarize(
    n_infectious = sum(is_infectious),
    n_suspected = sum(was_suspected & !is_infectious)
  ) %>%
  ungroup() %>%
  reshape2::melt(c("date", "date_in_model")) %>%
  mutate(
    variable = ifelse(grepl("infectious", variable), "Diagnosed", "Suspected"),
    variable = factor(variable, levels = c("Suspected", "Diagnosed"))
  )

diag_tb %>%
  filter(date_in_model != "Not modeled") %>%
  group_by(variable) %>%
  summarise(sum(value))

diag_tb_pl <- diag_tb %>%
  ggplot(aes(x = date, y = value, fill = date_in_model, alpha = variable)) +
  geom_bar(position = position_stack(), stat = "identity") +
  scale_x_date(date_labels = "%b %d", breaks = modeled_days) +
  scale_y_continuous(expand = c(0, 0)) +
  scale_fill_manual(values = c(wes_palette("Moonrise3"), "grey")) +
  scale_alpha_discrete(
    breaks = c("Diagnosed", "Suspected"),
    range = c(.33, 1)
  ) +
  labs(
    y = "Number of TB patients attending the clinic"
  ) +
  theme_custom(8) +
  theme(
    legend.position = "bottom",
    legend.title = element_blank(),
    legend.direction = "vertical",
    legend.box = "vertical",
    axis.title.x = element_blank(),
    axis.text.x = element_blank(),
    legend.key.width = unit(.2, "cm"),
    legend.key.height = unit(.3, "cm")
  ) +
  guides(
    fill = guide_legend(nrow = 1, order = 2),
    alpha = guide_legend(nrow = 1, order = 1)
  )

save_plot(
  diag_tb_pl,
  pdf_file = "results/data/diagnosed-tb-patients.png",
  w = 16, h = 10
)
```

```{r}
diag_tb %>%
  filter(variable == "Diagnosed") %>%
  ggplot(aes(x = value)) +
  geom_histogram()

counts <- table(diag_tb$value[diag_tb$variable == "Diagnosed"])
counts
df_counts <- data.frame(
  x = names(counts),
  n = as.numeric(counts),
  p = round(100 * as.numeric(counts) / sum(counts))
)

undiag_tb_pl <- df_counts %>%
  ggplot(aes(x = factor(x), y = p)) +
  geom_bar(
    stat = "identity",
    color = "grey0",
    fill = "grey70",
    alpha = .8
  ) +
  geom_text(
    aes(label = paste0("n" = n, " (", p, "%)")),
    vjust = -1,
    size = 8 / cm(1)
  ) +
  labs(
    x = "Number of undiagnosed TB patients", y = "Probability (%)"
  ) +
  scale_y_continuous(expand = expansion(mult = c(0, .12))) +
  theme_custom(8) +
  theme(plot.caption = element_text(size = 10))

save_plot(
  undiag_tb_pl,
  pdf_file = "results/inputs/undiagnosed-tb-patients.png",
  w = 8, h = 6
)
```

