---
title: "Descriptives Masi XOVIS Raw"
author: "Nicolas Banholzer"
date: "2023-02-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Libraries

```{r}
library(tidyverse)
library(reshape2)
library(lubridate)
library(gridExtra)
source("../utils/plotting.r")
source("../utils/spatial.R")
```


## Data

```{r}
files <- list.files("../data-raw/Masi/xovis", full.names = T)
files <- files[grepl("rds", files)]

masi <- do.call(rbind, lapply(files, function(f) readRDS(f) %>% 
                                dplyr::select(-point, -poly) %>%
                                mutate(file = f)))

masi$date <- format(masi$time, "%Y-%m-%d")

masi <- masi %>% dplyr::select(file, obs_id, date, time, x, y, height, everything())
```

## Descriptives

### Duration

```{r}
masi_by_oid <- masi %>%
  group_by(obs_id, date) %>%
  summarize(duration = n()) %>%
  ungroup() 

masi_by_oid %>%
  mutate(duration_cat = cut(duration, c(-Inf, 1, 5, 10, 30, 60, 300, 600, Inf))) %>%
  group_by(duration_cat) %>%
  summarize(n = n()) %>%
  ungroup() %>%
  mutate(p = n / sum(n)) %>%
  ggplot(aes(x = duration_cat, y = p)) +
  geom_bar(stat = "identity") +
  scale_y_continuous(labels = scales::percent) +
  labs(x = "Duration (in seconds)") +
  theme_bw2()
```


### Compute features

```{r}
masi <- masi %>%
  left_join(masi_by_oid, by = c("obs_id", "date")) %>%
  group_by(obs_id, date) %>%
  arrange(time) %>%
  mutate(distance = convert_dist( euclidean(lead(x), x, lead(y), y) ),
         height_ratio = lead(height) / height,
         heightdiff = lead(height) - height,
         timediff = as.numeric(difftime(lead(time), time, units = "sec"))) %>%
  ungroup()
```

### Distance

```{r}
# seating distance
masi %>%
  filter(is_seat, 
         timediff == 1,
         duration >= 60) %>%
  group_by(obs_id, date) %>%
  summarize(max_distance = max(distance)) %>%
  ungroup() %>%
  ggplot(aes(x = max_distance)) +
  geom_histogram()

# moving distance
masi %>%
  filter(!is_seat,
         !is_tbroom,
         timediff == 1,
         duration >= 60) %>%
  group_by(obs_id, date) %>%
  summarize(max_distance = max(distance)) %>%
  ungroup() %>%
  ggplot(aes(x = max_distance)) +
  geom_histogram()
```

### Height

```{r}
masi %>%
  filter(timediff == 1,
         duration >= 300) %>%
  group_by(obs_id, date) %>%
  summarize(hr = quantile(height_ratio, .95)) %>%
  ungroup() %>%
  ggplot(aes(x = hr)) +
  geom_histogram()

masi %>%
  filter(timediff == 1,
         duration >= 300) %>%
  group_by(obs_id, date) %>%
  summarize(hd = quantile(heightdiff, .05)) %>%
  ungroup() %>%
  ggplot(aes(x = hd)) +
  geom_histogram()
```

