---
title: "Environmental data"
author: "Nicolas Banholzer"
date: "2023-12-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries

```{r}
library(tidyverse)
library(tidybayes)
library(lubridate)

source("utils/plotting.r")
```


## Data

```{r}
dates <- as.Date(c(
  "2021-10-13",
  "2021-10-15",
  "2021-10-25",
  "2021-11-04",
  "2021-11-05"
))
abbr_dates <- format(dates, format = "%b %d")
cont_df <- readRDS("data-clean/environmental/continuous-iaq-data.rds") %>%
  mutate(
    time = as.POSIXct(
      format(date_time, format = "%H:%M:%S"),
      format = "%H:%M:%S"
    ),
    mthdy = factor(
      as.character(format(date, format = "%b %d")),
      levels = abbr_dates
    )
  )
aer <- readRDS("data-clean/environmental/air-change-rate.rds") %>%
  mutate(
    mthdy = factor(
      as.character(format(date, format = "%b %d")),
      levels = abbr_dates
    ),
    daytime = factor(daytime, levels = c("Morning", "Afternoon"))
  )
```


## Descriptives

### Summaries

```{r}
cont_df %>%
  summarize(
    across(c(co2, temperature, humidity),
      .fns = list(
        median = median,
        q25 = function(x) quantile(x, .25),
        q75 = function(x) quantile(x, .75)
      )
    )
  ) %>%
  gather() %>%
  mutate(value = round(value))
```

### CO2 over time

```{r}
co2_pl <- cont_df %>%
  mutate(time = floor_date(time, "10 minutes")) %>%
  group_by(mthdy, time, room) %>%
  summarize(co2 = mean(co2)) %>%
  ungroup() %>%
  mutate(room = factor(
    room,
    levels = c("Waiting room", "Corridor", "TB room")
  )) %>%
  ggplot(aes(x = time, y = co2, color = mthdy)) +
  geom_step() +
  facet_wrap(~room, ncol = 1) +
  scale_y_continuous(
    limits = c(350, 700),
    breaks = seq(350, 700, 100),
    expand = expansion(add = c(0, 0))
  ) +
  scale_x_datetime(
    expand = expansion(add = c(0, 1200)),
    date_breaks = "4 hours",
    date_labels = "%H:%M"
  ) +
  scale_color_manual(values = wes_palette("Moonrise3")) +
  labs(
    y = expression("CO"[2] * " (parts per million, ppm)")
  ) +
  theme_custom(8) +
  theme(
    axis.title.x = element_blank(),
    legend.title = element_blank(),
    legend.position = "bottom",
    legend.key.width = unit(0.275, "cm"),
    legend.key.height = unit(0.2, "cm")
  )

save_plot(
  co2_pl,
  pdf_file = "results/data/co2-levels-over-time.png",
  w = 16, h = 18
)
```


### Air change rate

```{r}
aer %>%
  group_by(room) %>%
  tidybayes::median_qi(aer, .width = .5) %>%
  mutate_if(is.numeric, round)

aer_pl <- aer %>%
  mutate(room = factor(
    room,
    levels = c("Waiting room", "Corridor", "TB room")
  )) %>%
  ggplot(aes(x = room, fill = room, y = aer)) +
  geom_boxplot() +
  # geom_jitter(
  #   mapping = aes(color = daytime),
  #   width = 0.2,
  #   height = 0,
  #   shape = 21
  # ) +
  scale_fill_manual(values = wes_palette("Royal2")[-1]) +
  scale_y_continuous(expand = expansion(mult = c(0, .05)), limits = c(0, NA)) +
  labs(
    y = "Air changes per hour",
    title = "d"
  ) +
  theme_custom(8) +
  theme(
    axis.title.x = element_blank(),
    legend.title = element_blank(),
    legend.position = c(0.8, 0.95)
  ) +
  guides(fill = "none")

saveRDS(
  aer_pl,
  "results/data/air-changes-per-hour.rds"
)

save_plot(
  aer_pl,
  pdf_file = "results/data/air-changes-per-hour.png",
  w = 8, h = 6
)
```

