---
title: "Patient movements"
author: "Nicolas Banholzer"
date: "2023-11-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries

```{r}
library(tidyverse)
library(lubridate)
library(parallel)
library(reshape2)

source("utils/plotting.r")
source("utils/spatial.r")
source("preprocessing/prep_building-rasterize.R")
```


## Data

### Tracking

```{r}
tracking_dates <- c(
  "2021-10-13", "2021-10-15", "2021-10-25", "2021-11-04", "2021-11-05"
)
abbr_dates <- format(as.Date(tracking_dates), format = "%b %d")

# spatial track counts
tracking_data <- do.call(
  rbind,
  lapply(
    list.files("data-raw/patient-tracking/annotated",
      full.names = TRUE
    ),
    readRDS
  )
) %>%
  rename(date_time = time) %>%
  mutate(date = as.Date(date_time)) %>%
  filter(date %in% tracking_dates) %>%
  filter(between(hour(date_time), 8, 15)) %>%
  mutate(
    room = ifelse(is_waitingroom, "Waiting room",
      ifelse(is_tbroom, "TB room",
        ifelse(is_passage, "Corridor", NA)
      )
    ),
    room = factor(room, levels = c("Waiting room", "Corridor", "TB room"))
  )

# track counts over time
track_count_time <- readRDS("data-clean/patient-tracking/tracks-over-time.rds")

# manually reconnected tracking data
df <- readRDS("data-clean/patient-tracking/augmented-and-combined-data.rds")

# filter considered clinical attendees
df_matched <- do.call(
  rbind,
  lapply(
    unique(df$date),
    function(d) {
      readRDS(paste0(
        "data-clean/patient-tracking/matched-clinical/",
        d, ".rds"
      ))
    }
  )
) %>%
  mutate(
    date = as.Date(time),
    hr = lubridate::hour(time)
  ) %>%
  filter(between(hr, 8, 15)) %>%
  filter(!(hr > 11 & date == "2021-10-15")) %>%
  group_by(date, patient_id) %>%
  slice(1) %>%
  ungroup() %>%
  mutate(patient_id = paste(date, patient_id))


df_filt <- filter(
  df,
  paste(date, patient_id) %in% df_matched$patient_id
)
```


## Descriptives

```{r}
n_distinct(paste(df$date, df$patient_id))
n_distinct(paste(df_filt$date, df_filt$patient_id))
df_filt %>%
  filter(tracking_end != "Possible HCW") %>%
  mutate(patient_id = paste(date, patient_id)) %>%
  dplyr::select(patient_id) %>%
  n_distinct()
```

### Tracking quality

```{r}
track_qual <- df_filt %>%
  group_by(date, patient_id) %>%
  slice(1) %>%
  ungroup() %>%
  dplyr::select(tracking_end) %>%
  unlist() %>%
  table()

track_qual_str <- paste0(
  names(track_qual),
  ": ",
  track_qual,
  " (",
  round(track_qual / sum(track_qual) * 100),
  "%)"
)
track_qual_str

df_filt %>%
  group_by(date, patient_id, tracking_end) %>%
  summarise(time_in_clinic = n() / 60) %>%
  ungroup() %>%
  group_by(tracking_end) %>%
  tidybayes::mean_qi(time_in_clinic, .width = .95) %>%
  ungroup()
```

### Time in clinic

```{r}
time_in_clin <- df_filt %>%
  group_by(date, patient_id) %>%
  summarize(
    tracking_end = first(tracking_end),
    `Clinic` = n(),
    `Waiting room` = sum(is_waitingroom),
    `TB room` = sum(is_tbroom),
    `Corridor` = sum(is_passage)
  ) %>%
  ungroup() %>%
  mutate(across(c(`Clinic`, `Waiting room`, `TB room`, `Corridor`), ~ .x / 60))

time_in_clin %>%
  filter(tracking_end != "Possible HCW") %>%
  tidybayes::median_qi(`Clinic`, .width = .5) %>%
  mutate_if(is.numeric, round)

time_in_clin_pl <- time_in_clin %>%
  filter(tracking_end != "Possible HCW") %>%
  dplyr::select(-tracking_end) %>%
  melt(c("date", "patient_id")) %>%
  filter(variable != "Clinic") %>%
  mutate(variable = factor(
    variable,
    levels = c("Waiting room", "Corridor", "TB room")
  )) %>%
  ggplot(aes(x = variable, fill = variable, y = value)) +
  geom_boxplot() +
  scale_y_sqrt(breaks = c(0, 10, 30, 60, 120, 180)) +
  scale_fill_manual(values = wes_palette("Royal2")) +
  labs(
    y = "Time in clinic (min)",
    title = "c"
  ) +
  theme_custom(8) +
  theme(
    legend.position = "none",
    legend.title = element_blank(),
    axis.title.x = element_blank(),
    plot.title.position = "plot"
  )

save_plot(
  time_in_clin_pl,
  pdf_file = "results/data/time-in-clinic.png", w = 8, h = 6
)
```


### Close contacts

```{r}
# number of close contacts <1m for >1min
no_close_contacts <- df_filt %>%
  unnest(cols = closeContacts) %>%
  group_by(date, patient_id, closeContacts, tracking_end) %>%
  summarise(
    n_time = n(),
    tracking_end = first(tracking_end)
  ) %>%
  ungroup() %>%
  group_by(date, patient_id) %>%
  summarize(
    n_cc = sum(n_time > 60),
    tracking_end = first(tracking_end)
  ) %>%
  ungroup()

no_close_contacts %>%
  filter(tracking_end != "Possible HCW") %>%
  tidybayes::median_qi(n_cc, .width = .5) %>%
  mutate_if(is.numeric, round)

time_close_contacts <- df_filt %>%
  mutate(has_closeContact = ifelse(
    sapply(closeContacts, length) >= 1, T, F
  )) %>%
  group_by(date, patient_id) %>%
  summarize(
    cc_time = sum(has_closeContact) / 60,
    tracking_end = first(tracking_end)
  ) %>%
  ungroup()

close_contact <- no_close_contacts %>%
  left_join(time_close_contacts) %>%
  left_join(time_in_clin)

cc_n_pl <- close_contact %>%
  filter(tracking_end != "Possible HCW") %>%
  ggplot(aes(x = n_cc)) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  labs(
    y = "Density", x = "Number of close contacts",
    title = "d"
    # subtitle = "Defined as <1m for >1min"
  ) +
  geom_density(fill = "grey70", color = "grey0", alpha = 0.8) +
  theme_custom(8) +
  theme(
    plot.title.position = "plot",
    plot.margin = margin(r = 11),
    plot.subtitle = element_text(margin = margin(b = 11))
  )

save_plot(
  cc_n_pl,
  pdf_file = "results/data/number-close-contacts.png", w = 5.3, h = 6
)

close_contact %>%
  filter(tracking_end != "Possible HCW") %>%
  tidybayes::median_qi(cc_time / Clinic * 100, .width = .5) %>%
  mutate_if(is.numeric, round)

cc_t_pl <- close_contact %>%
  filter(tracking_end != "Possible HCW") %>%
  ggplot(aes(x = cc_time / Clinic * 100)) +
  scale_x_continuous(expand = c(0, 0), limits = c(0, 100)) +
  scale_y_continuous(expand = c(0, 0)) +
  labs(
    y = "Density",
    x = "Time in close contact (%)",
    title = "e"
  ) +
  geom_density(
    fill = "grey70", color = "grey0", alpha = 0.8
  ) +
  theme_custom(8) +
  theme(
    plot.title.position = "plot",
    plot.margin = margin(r = 11)
  )

save_plot(
  cc_t_pl,
  pdf_file = "results/data/time-close-contacts.png", w = 5.3, h = 6
)
```


### Temporal hotspots

```{r}
track_count_time <- track_count_time %>%
  mutate(
    date = format(date, "%b %d"),
    date = factor(
      as.character(date),
      levels = c("Oct 13", "Oct 15", "Oct 25", "Nov 04", "Nov 05")
    ),
    time = as.POSIXct(format(
      date_time,
      format = "%H:%M:%S"
    ), format = "%H:%M:%S")
  )


time_pl <- track_count_time %>%
  group_by(time, room) %>%
  summarise(
    mv = mean(n),
    sv = sd(n)
  ) %>%
  ungroup() %>%
  mutate(
    lv = mv - sv,
    uv = mv + sv
  ) %>%
  ggplot(aes(x = time)) +
  geom_line(
    aes(y = mv, color = room)
  ) +
  geom_ribbon(
    aes(ymin = lv, ymax = uv, fill = room),
    alpha = 0.4
  ) +
  # ggh4x::facet_wrap2(~variable, axes = "x", remove_labels = "all") +
  coord_cartesian(expand = FALSE) +
  scale_x_datetime(
    date_breaks = "2 hours", date_labels = "%H:%M"
  ) +
  scale_fill_manual(values = wes_palette("Royal2")) +
  scale_color_manual(values = wes_palette("Royal2")) +
  labs(
    y = "Number of people",
    title = "b"
  ) +
  theme_custom(8) +
  theme(
    axis.title.x = element_blank(),
    legend.title = element_blank(),
    legend.position = "bottom",
    legend.key.width = unit(0.275, "cm"),
    legend.key.height = unit(0.2, "cm"),
    plot.margin = margin(r = 11)
  )

save_plot(
  time_pl,
  pdf_file = "results/data/no-people-over-time.png",
  w = 8, h = 8
)

time_by_day_pl <- track_count_time %>%
  mutate(
    time = as.POSIXct(
      format(date_time, format = "%H:%M:%S"),
      format = "%H:%M:%S"
    ),
    mthdy = factor(
      as.character(format(date, format = "%b %d")),
      levels = abbr_dates
    ),
    time = floor_date(time, "10 minutes")
  ) %>%
  group_by(mthdy, time, room) %>%
  summarize(n = mean(n)) %>%
  ungroup() %>%
  mutate(room = factor(
    room,
    levels = c("Waiting room", "Corridor", "TB room")
  )) %>%
  ggplot(aes(x = time, y = n, color = mthdy)) +
  geom_step() +
  facet_wrap(~room, ncol = 1) +
  scale_y_continuous(
    limits = c(0, NA),
    expand = expansion(add = c(0, 1))
  ) +
  scale_x_datetime(
    expand = expansion(add = c(0, 600)),
    date_breaks = "4 hours",
    date_labels = "%H:%M"
  ) +
  scale_color_manual(values = wes_palette("Moonrise3")) +
  labs(
    y = "Number of people"
  ) +
  theme_custom(8) +
  theme(
    axis.title.x = element_blank(),
    legend.title = element_blank(),
    legend.position = "bottom",
    legend.key.width = unit(0.275, "cm"),
    legend.key.height = unit(0.2, "cm")
  )

save_plot(
  time_by_day_pl,
  pdf_file = "results/data/no-people-over-time-by-day.png",
  w = 16, h = 18
)
```


### Spatial hotspots

```{r}
spatial_pl <- plot_spatial(
  ggplot(data = tracking_data, mapping = aes(x = x, y = y)) +
    geom_bin2d(binwidth = 200),
  text_descr = 8
) +
  labs(
    fill = "Number of tracks",
    title = "a"
  ) +
  scale_fill_gradientn(
    colours = RColorBrewer::brewer.pal(n = 9, name = "YlOrRd"),
    trans = "log10",
    labels = scales::comma,
    breaks = c(1, 10, 100, 1000, 10000)
  ) +
  theme(
    legend.position = "bottom",
    legend.direction = "horizontal",
    legend.key.height = unit(0.2, "cm"),
    legend.key.width = unit(1, "cm")
  ) +
  guides(fill = guide_colorbar(title.vjust = 1))

save_plot(
  spatial_pl,
  pdf_file = "results/data/no-people-spatial.png",
  w = 8, h = 8
)
```


### Example tracks

```{r}
# unique id
df$day_pid <- paste("Date:", df$date, " |  ID:", df$patient_id)

# random sample tracks
ex_pid <- df %>%
  filter(tracking_end != "Possible HCW") %>%
  group_by(day_pid) %>%
  slice(1) %>%
  ungroup() %>%
  group_by(tracking_end) %>%
  sample_n(3) %>%
  ungroup() %>%
  dplyr::select(day_pid) %>%
  unlist()
ex_df <- df %>% filter(day_pid %in% ex_pid)
ex_df_se <- ex_df %>%
  group_by(day_pid) %>%
  slice(1, n()) %>%
  mutate(type = factor(c("Start", "End"), levels = c("Start", "End"))) %>%
  ungroup()

# manual sample of tracks
ex_pid_man <- c(
  "Date: 2021-10-25  |  ID: 4649", # Entered + Exited, including TB room stay
  # "2021-10-13 6297", # Lost Exit, only waiting room
  # "2021-11-04 12860", # (Entered) + Exited, waiting room and corridor
  # "2021-10-13 9346", # Entered + Exited, including TB room
  # "2021-11-05 16625", # Entered + (Exited), only waiting room
  "Date: 2021-10-25  |  ID: 9526", # Lost Exit, waiting room and corridor
  "Date: 2021-11-04  |  ID: 9841", # Entered = (Exited), waiting room and corridor
  "Date: 2021-10-15  |  ID: 8644" # Entered + Exited, including TB room
  # "2021-10-15 9419" # Lost Enter
)
ex_df_man <- df %>% filter(day_pid %in% ex_pid_man)
ex_df_man_se <- ex_df_man %>%
  group_by(day_pid) %>%
  slice(1, n()) %>%
  mutate(type = factor(c("Start", "End"), levels = c("Start", "End"))) %>%
  ungroup()

# plot
ex_tracks <- plot_spatial(
  ggplot() +
    geom_path(
      data = ex_df_man,
      mapping = aes(x = x, y = y),
      color = "darkred"
    ) +
    geom_point(
      data = ex_df_man_se,
      mapping = aes(x = x, y = y, shape = type),
      size = 2
    ) +
    facet_wrap(~day_pid, ncol = 2) +
    scale_shape_manual(values = c(1, 13)),
  text_descr = 8
) +
  theme(
    legend.position = "none"
  )

save_plot(
  ex_tracks,
  pdf_file = "results/data/example-patient-tracks.png",
  w = 16, h = 12
)
```