---
title: "Quanta concentration and Transmission risk"
author: "Nicolas Banholzer"
date: "2023-12-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries

```{r}
library(tidyverse)
library(reshape2)
library(rstanarm)
library(tidybayes)
library(gganimate)

source("utils/plotting.r")
source("utils/tex.r")
source("models/stm-v2.R")

# building
cellSize <- 250
source("preprocessing/prep_building-rasterize.R")

# load tracking and environmental data
track <- readRDS("data-clean/patient-tracking/augmented-and-combined-data.rds")
aer <- readRDS("data-clean/environmental/air-change-rate.rds") %>%
  mutate(daytime = factor(daytime, levels = c("Morning", "Afternoon")))
```

## Illustration

```{r illustration}
# data
mth <- 10
dy <- 25
sim <- 1
param_1025 <- readRDS(
  paste0(
    "simulations/", "/", "sim-param-",
    2021, "-", mth, "-", dy, ".rds"
  )
)
track_1025 <- readRDS(
  paste0(
    "simulations/", "/", "tracking-df-",
    250, "px-", 2021, "-", mth, "-", dy, ".rds"
  )
)
track_undiag <- track_1025 %>%
  dplyr::filter(tracking_end != "Possible HCW")
track_diag <- dplyr::filter(track_1025, is_infectious)
track_undiag <- dplyr::filter(
  track_undiag, !is_infectious | is.na(is_infectious)
)
track_tb_all <- rbind(
  track_diag,
  filter(
    track_undiag,
    patient_id %in% param_1025[[paste0("undiagTB", "_", "du")]][[sim]]
  )
)
aer_df <- readRDS("data-clean/environmental/air-change-rate.rds") %>%
  filter(
    month(date) == as.numeric(mth),
    day(date) == as.numeric(dy)
  )

# time
date <- paste0("2021-", mth, "-", dy)
t_start <- as.POSIXct(paste(date, "08:00:00"))
midday <- as.POSIXct(paste(date, "12:00:00"))
t_end <- as.POSIXct(paste(date, "16:00:00"))
tt <- seq.POSIXt(t_start, t_end, by = "1 sec")
tt_morn <- seq.POSIXt(t_start, midday, by = "1 sec")
tt_noon <- seq.POSIXt(midday + 1, t_end, by = "1 sec")
midday_idx <- which(tt == midday)


# simulation
ct_by_room <- list()
for (room in c("Waiting room", "Corridor", "TB room")) {
  print(paste0("- ", room))

  # room setup
  if (room == "Waiting room") {
    # initial quanta concentration matrix
    c0 <- sP_to_matrix(waiting_room)

    # (no) TB patients in room
    track_tb <- filter(track_tb_all, is_waitingroom)

    # room dimension
    roomDim <- dimWR
  } else if (room == "Corridor") {
    # initial quanta concentration matrix
    c0 <- sP_to_matrix(corridor)

    # TB patients in room
    track_tb <- filter(track_tb_all, is_passage)

    # room dimension
    roomDim <- dimCD
  } else if (room == "TB room") {
    # initial quanta concentration matrix
    c0 <- sP_to_matrix(tb_room)

    # TB patients in room
    track_tb <- filter(track_tb_all, is_tbroom)

    # room dimension
    roomDim <- dimTB
  } else {
    stop("Error: Room invalid.")
  }

  # add quanta generation rate per second by activity level
  track_tb <- track_tb %>%
    dplyr::select(time, cell_x, cell_y, activity) %>%
    rename(x = cell_x, y = cell_y) %>%
    mutate(
      q = ifelse(activity == 1,
        param_1025$q_wait[param_1025$sim == sim],
        param_1025$q_walk[param_1025$sim == sim]
      ),
      q = q * param_1025$mask_red[param_1025$sim == sim],
      q = q / 3600
    )

  # quanta conc in the morning
  print("-- morning")
  track_tb_morn <- filter(track_tb, time <= midday)
  track_tb_morn$t <- as.numeric(difftime(
    track_tb_morn$time, t_start,
    units = "sec"
  ))

  ct_by_room[[room]] <- stm(
    time = tt_morn,
    c0 = c0,
    inf = dplyr::select(track_tb_morn, -time, -activity),
    cellLength = convert_dist(cellSize),
    pd = 0,
    vol = prod(roomDim),
    aer = aer_df$aer[aer_df$room == room & aer_df$daytime == "Morning"] / 3600,
    lambda = param_1025$viral_inact[param_1025$sim == sim] / 3600,
    deposit = 0
  )
}

# get subset
subset_qc <- function(t) {
  # quanta conc
  qc_wr <- melt(ct_by_room[["Waiting room"]][, , t]) %>%
    rename(y = Var1, x = Var2) %>%
    mutate(room = "Waiting room", across(c(x, y), as.numeric))
  qc_cr <- melt(ct_by_room[["Corridor"]][, , t]) %>%
    rename(y = Var1, x = Var2) %>%
    mutate(room = "Corridor", across(c(x, y), as.numeric))
  qc_tb <- melt(ct_by_room[["TB room"]][, , t]) %>%
    rename(y = Var1, x = Var2) %>%
    mutate(room = "TB room", across(c(x, y), as.numeric))

  # link to building
  qc <- rbind(qc_wr, qc_cr, qc_tb)
  qc <- left_join(roomCoord, qc, by = c("x", "y", "room")) %>%
    mutate(
      id = paste0("ID", id),
      t = t
    )

  return(qc)
}

track_tb_all %>%
  filter(between(
    time,
    as.POSIXct(paste(date, "09:41:00")),
    as.POSIXct(paste(date, "09:45:00"))
  )) %>%
  ggplot(aes(x = x, y = y, color = factor(patient_id))) +
  geom_path()

tt_selected <- seq.POSIXt(
  as.POSIXct(paste(date, "09:41:00")),
  as.POSIXct(paste(date, "09:45:00")),
  by = "1 sec"
)
tt_selected_idx <- as.numeric(tt_selected - t_start, unit = "secs")
names(tt_selected) <- tt_selected_idx

qc_sub <- do.call(
  rbind,
  parallel::mclapply(tt_selected_idx, subset_qc, mc.cores = 4)
) %>%
  mutate(t = t - min(tt_selected_idx))

# animated plot
qc_anim_pl <- ggplot(
  data = left_join(
    fortify(waiting_room),
    filter(qc_sub, room == "Waiting room"),
    by = c("id")
  ),
  mapping = aes(x = long, y = lat, group = group, fill = value)
) +
  geom_polygon() +
  coord_cartesian(expand = FALSE) +
  scale_fill_gradientn(
    colours = RColorBrewer::brewer.pal(n = 9, name = "YlOrRd"),
    labels = function(x) round(1e3 * x / (0.25^2 * 3), 1)
  ) +
  theme_custom(14) +
  theme(
    axis.text = element_blank(),
    axis.title = element_blank(),
    axis.ticks = element_blank(),
    legend.position = "bottom",
    panel.background = element_rect(
      fill = RColorBrewer::brewer.pal(n = 9, name = "YlOrRd")[1]
    ),
    panel.grid.major = element_blank(), panel.grid.minor = element_blank()
  ) +
  transition_time(t) +
  labs(
    subtitle = "Time (secs): {frame_time}",
    title = "Quanta concentration in the waiting room on Oct 25 between 9:41 and 09:45am", # nolint
    fill = expression("Quanta/m"^3 * " x 10"^-3)
  )

gganimate::animate(
  qc_anim_pl,
  duration = 30,
  width = 1.850877 * 600,
  height = 600,
  renderer = gifski_renderer(),
  nframes = length(tt_selected_idx)
)

gganimate::anim_save("results/modeling/illustrated-quanta-conc-over-time.gif")
```

## Main

### Quanta conc

```{r}
main_qc <- data.frame(
  files = list.files("simulations/main/",
    full.names = TRUE, pattern = "quanta_conc-.*.txt$",
    recursive = TRUE
  )
) %>%
  mutate(
    room = ifelse(grepl("Waiting", files), "Waiting room",
      ifelse(grepl("Corridor", files), "Corridor", "TB room")
    ),
    daytime = ifelse(grepl("morning", files), "morning", "afternoon")
  )

mean_qc <- function(file) {
  df <- read.table(file)
  colnames(df) <- c("sim", "x", "y", "value")
  df <- df %>%
    group_by(x, y) %>%
    summarize(value = mean(value)) %>%
    ungroup()
  return(df)
}

main_qc$value <- lapply(main_qc$files, mean_qc)

main_mean_qc <- main_qc %>%
  unnest(value) %>%
  group_by(room, daytime, x, y) %>%
  summarize(
    value = mean(value)
  ) %>%
  ungroup()

# example translation
source("utils/trans_risk.r")
IR_sit <- (.5 * IR("sitting", "male") + .5 * IR("sitting", "female")) / 3600
WR_vol <- convert_dist(cellSize)^2 * dimWR[3]
wr_morn <- main_mean_qc %>%
  filter(room == "Waiting room", daytime == "morning") %>%
  pull(value) %>%
  max()
wr_noon <- main_mean_qc %>%
  filter(room == "Waiting room", daytime == "afternoon") %>%
  pull(value) %>%
  max()
round((1 - exp(-wr_morn * 3600 * IR_sit / WR_vol)) * 100, 3)
round((1 - exp(-wr_noon * 3600 * IR_sit / WR_vol)) * 100, 3)

# link to building
main_mean_qc <- left_join(roomCoord,
  main_mean_qc %>% dplyr::select(room, daytime, x, y, value),
  by = c("x", "y", "room")
) %>%
  mutate(
    id = paste0("ID", id),
    daytime = factor(
      ifelse(daytime == "morning", "Morning", "Afternoon"),
      levels = c("Morning", "Afternoon")
    )
  )

# plot
mean_quanta_pl <- plot_spatial(
  ggplot(mapping = aes(x = long, y = lat, group = group, fill = value)) +
    facet_wrap(~daytime) +
    geom_polygon(
      data = left_join(
        fortify(waiting_room),
        filter(main_mean_qc, room == "Waiting room"),
        by = c("id")
      )
    ) +
    geom_polygon(
      data = left_join(
        fortify(corridor),
        filter(main_mean_qc, room == "Corridor"),
        by = c("id")
      )
    ) +
    geom_polygon(
      data = left_join(fortify(tb_room),
        filter(main_mean_qc, room == "TB room"),
        by = c("id")
      )
    ) +
    labs(
      fill = expression("Mean quanta concentration (quanta m"^-3 * " " * "x 10"^-3 * ")")
    ) +
    scale_fill_gradientn(
      colours = RColorBrewer::brewer.pal(n = 9, name = "YlOrRd"),
      labels = function(x) round(1e3 * x / (0.25^2 * 3), 1)
    ),
  8
) +
  theme(
    legend.position = "bottom",
    legend.direction = "horizontal",
    legend.key.height = unit(0.2, "cm"),
    legend.key.width = unit(1.5, "cm"),
    legend.title = element_text(margin = margin(r = 10))
  )

save_plot(
  mean_quanta_pl,
  "results/modeling/mean-quanta-concentration.png",
  w = 16,
  h = 8
)
```

### Trans risk

```{r}
average_trans_risk <- function(file) {
  average_tr <- read.table(file) %>%
    set_names(c("sim", "patient_id", "P")) %>%
    mutate(
      mthdy = stringi::stri_extract(file, regex = "\\d{2}-\\d{2}"),
      patient_id = paste(mthdy, patient_id, sep = "-")
    ) %>%
    group_by(patient_id) %>%
    summarize(
      P_mean = mean(P),
      P025 = quantile(P, .025),
      P975 = quantile(P, .975),
      P25 = quantile(P, .25),
      P75 = quantile(P, .75),
      P20 = quantile(P, .2),
      P80 = quantile(P, .8)
    ) %>%
    ungroup() %>%
    left_join(track %>%
      mutate(
        mth = lubridate::month(time),
        dy = lubridate::day(time)
      ) %>%
      group_by(patient_id, mth, dy) %>%
      slice(1) %>%
      ungroup() %>%
      mutate(dy = ifelse(nchar(dy) == 1, paste0("0", dy), dy)) %>%
      mutate(patient_id = paste(
        mth, dy,
        patient_id,
        sep = "-"
      )) %>%
      dplyr::select(patient_id, tracking_end)) %>%
    filter(tracking_end != "Possible HCW") %>%
    dplyr::select(-tracking_end) %>%
    mutate(
      P_col = ifelse(P_mean < .001, "Low",
        ifelse(P_mean < .01, "Medium", "High")
      ),
      P_col = factor(P_col, levels = c("Low", "Medium", "High"))
    )
  return(average_tr)
}

# average risk
main_tr <- data.frame(
  files = list.files("simulations/main/",
    full.names = TRUE, pattern = "trans-risk.txt$",
    recursive = TRUE
  )
)
main_tr$value <- lapply(main_tr$files, average_trans_risk)

main_tr <- main_tr %>%
  unnest(value) %>%
  dplyr::select(-files)

# annotation
annotate_average_trans_risk <- function(tr) {
  roi_annon <- tr %>%
    summarize(
      mean_P = mean(P_mean),
      lower_P = quantile(P_mean, .2),
      upper_P = quantile(P_mean, .8)
    ) %>%
    mutate(
      across(c(mean_P, lower_P, upper_P), ~ round_k(100 * .x, 2)),
      lab = paste0(
        mean_P, "%",
        " (80%-CrI ", lower_P, "% – ", upper_P, "%)"
      )
    )
  return(roi_annon)
}

main_annon <- annotate_average_trans_risk(main_tr)

main_annon
```

```{r}
main_tr <- main_tr %>%
  mutate(P_unc = P80 - P20)

hr_lu_pt <- main_tr %>%
  filter(P_unc < .25 / 100, P_mean > 0.25 / 100) %>%
  head(1)

main_focus_pl <- main_tr %>%
  ggplot(aes(x = P_unc, y = P_mean)) +
  geom_point(shape = 4) +
  annotate(
    "point",
    x = hr_lu_pt$P_unc,
    y = hr_lu_pt$P_mean,
    size = 7,
    shape = 1,
    color = "red"
  ) +
  annotate(
    geom = "segment",
    x = hr_lu_pt$P_unc + .00002,
    y = hr_lu_pt$P_mean + .0004,
    xend = hr_lu_pt$P_unc + .00008,
    yend = hr_lu_pt$P_mean + .004,
    arrow = arrow(length = unit(0.1, "cm")),
    color = "red"
  ) +
  annotate(
    geom = "text",
    x = hr_lu_pt$P_unc + .00008,
    y = hr_lu_pt$P_mean + .004,
    label = "Moderate risk,\nlow uncertainty",
    hjust = -.1,
    size = 6.5 / cm(1),
    color = "red"
  ) +
  scale_y_continuous(
    expand = expansion(mult = c(0.01, 0.01)),
    limits = c(0, .01),
    breaks = seq(0, .01, .0025),
    labels = function(x) round_k(100 * x, 3)
  ) +
  scale_x_continuous(
    expand = expansion(mult = c(0.01, 0.01)),
    limits = c(0, .002),
    breaks = seq(0, .002, .0005),
    labels = function(x) round_k(100 * x, 3)
  ) +
  labs(
    x = "Uncertainty (80%-CrI, pp)",
    y = "Mean risk of infection (%)"
  ) +
  theme_bw2() +
  theme(
    plot.title.position = "plot",
    plot.title = element_text(size = 10, face = 2),
    plot.margin = margin(.5, .5, .5, .5, "cm")
  )

save_plot(
  main_focus_pl,
  "results/modeling/patient-risk-focus-plot.png",
  w = 12,
  h = 10
)
```

### Association

```{r}
# process tracking data
track_daytime <- track %>%
  mutate(h = lubridate::hour(time)) %>%
  group_by(date, patient_id) %>%
  summarize(
    dur_morning = sum(h < 12),
    dur_afternoon = sum(h >= 12),
    tracking_end = tracking_end[1]
  ) %>%
  ungroup() %>%
  mutate(daytime = ifelse(dur_morning > dur_afternoon, "Morning", "Afternoon"))

time_in_clin <- track %>%
  group_by(date, patient_id) %>%
  summarize(
    `Clinic` = n(),
    `Waiting room` = sum(is_waitingroom),
    `TB room` = sum(is_tbroom),
    `Corridor` = sum(is_passage)
  ) %>%
  ungroup() %>%
  mutate(across(c(`Clinic`, `Waiting room`, `TB room`, `Corridor`), ~ .x / 60))

no_close_contacts <- track %>%
  unnest(cols = closeContacts) %>%
  group_by(date, patient_id, closeContacts, tracking_end) %>%
  summarise(n_time = n()) %>%
  ungroup() %>%
  group_by(date, patient_id) %>%
  summarize(n_cc = sum(n_time > 60)) %>%
  ungroup()

time_close_contacts <- track %>%
  mutate(has_closeContact = ifelse(
    sapply(closeContacts, length) >= 1, TRUE, FALSE
  )) %>%
  group_by(date, patient_id) %>%
  summarize(cc_time = sum(has_closeContact) / 60) %>%
  ungroup()

# merge data
track_ft <- left_join(
  track_daytime,
  left_join(left_join(
    time_in_clin,
    no_close_contacts
  ), time_close_contacts)
) %>%
  mutate(n_cc = ifelse(is.na(n_cc), 0, n_cc)) %>%
  rename(time_in_clinic = `Clinic`) %>%
  dplyr::select(
    date,
    patient_id,
    tracking_end,
    daytime,
    time_in_clinic,
    n_cc,
    cc_time
  )

assoc_df <- track_ft %>%
  # left_join(
  #   aer %>%
  #     filter(room == "Waiting room") %>%
  #     dplyr::select(date, daytime, aer)
  # ) %>%
  mutate(patient_id = paste(
    lubridate::month(date),
    lubridate::day(date),
    patient_id,
    sep = "-"
  )) %>%
  left_join(
    main_tr %>%
      dplyr::select(patient_id, P_mean)
  )

# risk per hour in clinic
assoc_df %>%
  filter(tracking_end != "Possible HCW") %>%
  mutate(
    rph = 60 * P_mean / time_in_clinic,
    rpy = 1 - (1 - rph)^12
  ) %>%
  mean_qi(rph, rpy, .width = .8, na.rm = TRUE) %>%
  mutate_if(is.numeric, ~ round_k(100 * .x, 2)) %>%
  unlist()

# model
amod <- stan_betareg(P_mean ~ time_in_clinic + n_cc + cc_time,
  data = assoc_df %>% mutate(
    n_cc = n_cc + 1, cc_time = cc_time + 1 / 60,
    across(c(time_in_clinic, n_cc, cc_time), log2)
  ),
  seed = 12345, cores = 4
)

amod_est <- spread_draws(amod, time_in_clinic, n_cc, cc_time) %>%
  reshape2::melt(c(".chain", ".iteration", ".draw")) %>%
  mutate(value = exp(value))

amod_est %>%
  group_by(variable) %>%
  summarize(
    lower = quantile(value, .025),
    mean = mean(value),
    upper = quantile(value, .975)
  ) %>%
  mutate(across(c(lower, mean, upper), ~ round_k(.x, 2)))
```

## Comparison with temporal model

```{r}
# files
files_temp <- list.files("simulations/temporal/",
  full.names = TRUE, pattern = "trans-risk",
  recursive = TRUE
)

temp_tr <- map_dfr(files_temp, average_trans_risk)
temp_annon <- annotate_average_trans_risk(temp_tr)

# comparison with temporal model
mod_comp <- left_join(
  temp_tr %>%
    dplyr::select(patient_id, P_mean) %>%
    rename(`Temporal model` = P_mean),
  main_tr %>%
    dplyr::select(patient_id, P_mean) %>%
    mutate(`Spatiotemporal model` = P_mean)
) %>%
  mutate(
    ratio = abs(`Spatiotemporal model` - `Temporal model`) / `Temporal model` * 100
  )

summary(mod_comp$ratio)
```


## IPC comparison

```{r additional-analyses}
# files
files_nm <- list.files("simulations/nomasks/",
  full.names = TRUE, pattern = "trans-risk",
  recursive = TRUE
)
files_vent <- list.files("simulations/vent/",
  full.names = TRUE, pattern = "trans-risk",
  recursive = TRUE
)
files_nmvent <- list.files("simulations/nomasksvent/",
  full.names = TRUE, pattern = "trans-risk",
  recursive = TRUE
)

# average risk
nm_tr <- map_dfr(files_nm, average_trans_risk)
vent_tr <- map_dfr(files_vent, average_trans_risk)
nmvent_tr <- map_dfr(files_nmvent, average_trans_risk)

nm_tr %>%
  group_by(P_col) %>%
  summarise(n = n()) %>%
  ungroup() %>%
  mutate(prop = round(n / sum(n) * 100, 0))

vent_tr %>%
  group_by(P_col) %>%
  summarise(n = n()) %>%
  ungroup() %>%
  mutate(prop = round(n / sum(n) * 100, 0))

nmvent_tr %>%
  group_by(P_col) %>%
  summarise(n = n()) %>%
  ungroup() %>%
  mutate(prop = round(n / sum(n) * 100, 0))

main_tr %>%
  dplyr::select(patient_id, P_mean) %>%
  rename(`Spatiotemporal model` = P_mean) %>%
  left_join(
    nm_tr %>%
      dplyr::select(patient_id, P_mean) %>%
      rename(`No mask wearing` = P_mean)
  ) %>%
  left_join(
    vent_tr %>%
      dplyr::select(patient_id, P_mean) %>%
      rename(`Lower ventilation` = P_mean)
  ) %>%
  left_join(
    nmvent_tr %>%
      dplyr::select(patient_id, P_mean) %>%
      rename(`No mask wearing and lower ventilation` = P_mean)
  ) %>%
  mutate(
    mask_factor = `No mask wearing` / `Spatiotemporal model`,
    vent_factor = `Lower ventilation` / `Spatiotemporal model`,
    nmvent_factor = `No mask wearing and lower ventilation` / `Spatiotemporal model`
  ) %>%
  mean_qi(mask_factor, vent_factor, nmvent_factor) %>%
  gather() %>%
  head(9) %>%
  mutate(value = round(as.numeric(value), 1))

# combine
tr_comp <- rbind(
  main_tr %>% mutate(scenario = "a   Mask use and high ventilation"),
  nm_tr %>% mutate(scenario = "b   No mask use and high ventilation"),
  vent_tr %>% mutate(scenario = "c   Mask use and normal ventilation"),
  nmvent_tr %>% mutate(scenario = "d   No mask use and normal ventilation")
) %>%
  mutate(scenario = factor(scenario, levels = unique(scenario)))

# annotation
nm_annon <- annotate_average_trans_risk(nm_tr)
vent_annon <- annotate_average_trans_risk(vent_tr)
nmvent_annon <- annotate_average_trans_risk(nmvent_tr)

annon_comp <- rbind(
  main_annon %>% mutate(scenario = "a   Mask use and high ventilation"),
  nm_annon %>% mutate(scenario = "b   No mask use and high ventilation"),
  vent_annon %>% mutate(scenario = "c   Mask use and normal ventilation"),
  nmvent_annon %>% mutate(scenario = "d   No mask use and normal ventilation")
) %>%
  mutate(scenario = factor(scenario, levels = unique(scenario)))

# plot mean
mean_roi_comp_pl <- ggplot(
  tr_comp,
  aes(x = P_mean)
) +
  geom_histogram(
    mapping = aes(fill = P_col),
    binwidth = .0005,
    boundary = 1
  ) +
  geom_text(
    data = annon_comp,
    mapping = aes(x = Inf, y = Inf, label = lab),
    size = 8 / cm(1),
    hjust = 1, vjust = 2
  ) +
  facet_wrap(~scenario, ncol = 2) +
  scale_fill_manual(values = wes_palette("Darjeeling1")[c(2, 3, 1)]) +
  coord_cartesian(expand = FALSE) +
  scale_x_continuous(
    labels = function(x) x * 100,
    breaks = c(0, 0.001, 0.005, 0.01, 0.015, 0.02),
    limits = c(0, 0.02)
  ) +
  scale_y_sqrt(
    labels = scales::comma,
    breaks = c(0, 25, 100, 250, 500, 1000),
    limits = c(0, NA)
  ) +
  labs(
    x = "Risk of infection (%)",
    y = "Number of clinical attendees"
  ) +
  theme_custom() +
  theme(
    legend.position = "bottom",
    legend.title = element_blank(),
    legend.key.height = unit(.6, "cm"),
    legend.key.width = unit(.4, "cm"),
    strip.text = element_text(hjust = 0)
  )

save_plot(
  mean_roi_comp_pl,
  "results/modeling/mean-roi-comparison.png",
  w = 16,
  h = 12
)
```

## Additional analysis

```{r} 
files_prev <- list.files("simulations/prevalence/",
  full.names = TRUE, pattern = "trans-risk",
  recursive = TRUE
)
files_susp <- list.files("simulations/suspected/",
  full.names = TRUE, pattern = "trans-risk",
  recursive = TRUE
)

prev_tr <- map_dfr(files_prev, average_trans_risk)
susp_tr <- map_dfr(files_susp, average_trans_risk)

tr_assum <- rbind(
  prev_tr %>% mutate(scenario = "a   Prevalence-based model"),
  susp_tr %>% mutate(scenario = "b   Suspected-based model")
) %>%
  mutate(scenario = factor(scenario, levels = unique(scenario)))

prev_annon <- annotate_average_trans_risk(prev_tr)
susp_annon <- annotate_average_trans_risk(susp_tr)

annon_assum <- rbind(
  prev_annon %>% mutate(scenario = "a   Prevalence-based model"),
  susp_annon %>% mutate(scenario = "b   Suspected-based model")
) %>%
  mutate(scenario = factor(scenario, levels = unique(scenario)))

# plot mean
mean_roi_assum_pl <- ggplot(
  tr_assum,
  aes(x = P_mean)
) +
  geom_histogram(
    mapping = aes(fill = P_col),
    binwidth = .0005,
    boundary = 1
  ) +
  geom_text(
    data = annon_assum,
    mapping = aes(x = Inf, y = Inf, label = lab),
    size = 8 / cm(1),
    hjust = 1, vjust = 2
  ) +
  facet_wrap(~scenario, ncol = 2) +
  scale_fill_manual(values = wes_palette("Darjeeling1")[c(2, 3, 1)]) +
  coord_cartesian(expand = FALSE) +
  scale_x_continuous(
    labels = function(x) x * 100,
    breaks = c(0, 0.001, 0.005, 0.01, 0.015, 0.02),
    limits = c(0, 0.02)
  ) +
  scale_y_sqrt(
    labels = scales::comma,
    breaks = c(0, 25, 100, 250, 500, 1000),
    limits = c(0, NA)
  ) +
  labs(
    x = "Risk of infection (%)",
    y = "Number of clinical attendees"
  ) +
  theme_custom() +
  theme(
    legend.position = "bottom",
    legend.title = element_blank(),
    legend.key.height = unit(.6, "cm"),
    legend.key.width = unit(.4, "cm"),
    panel.spacing = unit(2, "cm"),
    strip.text = element_text(hjust = 0)
  )

save_plot(
  mean_roi_assum_pl,
  "results/modeling/mean-roi-assumptions.png",
  w = 16,
  h = 7
)
```